-- Additive canonical landing table for validated sdar.evidence/v1 records.
-- This migration intentionally contains no destructive or mutating DDL.

CREATE DATABASE IF NOT EXISTS sdar_core;

CREATE TABLE IF NOT EXISTS sdar_core.sdar_evidence_v1_record
(
    row_id FixedString(64),
    fact_id String,
    contract_version LowCardinality(String),
    export_id String,
    export_revision UInt64,
    source_id String,
    source_type LowCardinality(String),
    batch_node_id String,
    batch_hash String,
    first_sequence String,
    last_sequence String,
    evidence_sequence String,
    record_id String,
    record_family LowCardinality(String),
    record_type LowCardinality(String),
    schema_name String,
    schema_version UInt32,
    source_system LowCardinality(String),
    source_table String,
    source_record_id String,
    source_revision String,
    tenant_id Nullable(String),
    user_scope_id Nullable(String),
    project_id Nullable(String),
    environment LowCardinality(String),
    node_id Nullable(String),
    task_id Nullable(String),
    context_id Nullable(String),
    episode_id Nullable(String),
    run_id Nullable(String),
    goal_id Nullable(String),
    goal_version Nullable(UInt32),
    plan_id Nullable(String),
    plan_version Nullable(UInt32),
    skill_execution_id Nullable(String),
    capability_binding_id Nullable(String),
    remote_task_binding_id Nullable(String),
    correlation_id String,
    causation_id Nullable(String),
    delivery_guarantee LowCardinality(String),
    evaluation_role LowCardinality(String),
    observation_generation Nullable(UInt8),
    evidence_refs Array(String),
    artifact_refs Array(String),
    payload_hash String,
    payload_json String CODEC(ZSTD(3)),
    record_json String CODEC(ZSTD(3)),
    occurred_at DateTime64(3, 'UTC'),
    recorded_at DateTime64(3, 'UTC'),
    received_at DateTime64(3, 'UTC'),
    ingested_at DateTime64(3, 'UTC'),
    wal_partition Nullable(String),
    wal_offset Nullable(UInt64),
    wal_written_at Nullable(DateTime64(3, 'UTC')),
    wal_payload_hash Nullable(String),
    projected_at DateTime64(3, 'UTC'),
    projection_id LowCardinality(String),
    projection_version String
)
ENGINE = ReplacingMergeTree(projected_at)
PARTITION BY toYYYYMM(occurred_at)
ORDER BY (record_type, record_id, row_id);
